---

- name: Ensure AWS directory exists
  become: True
  become_user: "{{ item.username }}"
  file:
    path: "$HOME/.aws"
    state: directory
    owner: "{{ item.username }}"
    group: "{{ item.group | default(item.username) }}"
  with_items: "{{ aws_cli_users }}"

- name: Create AWS creds file
  become: True
  become_user: "{{ item.username }}"
  template:
    src: aws_creds.j2
    dest: "$HOME/.aws/credentials"
    owner: "{{ item.username }}"
    group: "{{ item.group | default(item.username) }}"
  with_items: "{{ aws_cli_users }}"

- name: Create AWS config file
  become: True
  become_user: "{{ item.username }}"
  template:
    src: aws_config.j2
    dest: "$HOME/.aws/config"
    owner: "{{ item.username }}"
    group: "{{ item.group | default(item.username) }}"
  with_items: "{{ aws_cli_users }}"
