---

- hosts: aws
  roles:
    - role_under_test
  pre_tasks:
    - name: Create a test user
      user:
        name: test
        shell: /bin/bash
        comment: Test user
        createhome: True
  vars_files:
    - shared.yml
